version: '3'
services:
        database:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: postgres
        rstudio:
                image: rocker/verse
                ports:
                        - 8787:8787
                volumes:
                        - .:/home/rstudio/dev
                environment:
                        PASSWORD: 123
        pgadmin:
                image: dpage/pgadmin4
                depends_on:
                        - database
                restart: always
                ports:
                        - 80:80
                environment:
                        PGADMIN_DEFAULT_PASSWORD: postgres
                        PGADMIN_DEFAULT_EMAIL: rodriguezagustin@buenosaires.gob.ar
