version: '3'
services:
        database:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: postgres
        jupyter:
                image: jupyter/datascience-notebook
                ports:
                        - 8888:8888
        pgadmin:
                image: dpage/pgadmin4
                depends_on:
                        - database
                restart: always
                ports:
                        - 80:80
                environment:
                        PGADMIN_DEFAULT_PASSWORD: postgres
                        PGADMIN_DEFAULT_EMAIL: rodriguezagustin@buenosaires.gob.ar
